spring.application.name=bidwarsonline
 
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.pcjbzjbfglmrllxtbwfd
spring.datasource.password=X-!J&C-q-ar9y%c
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
jwt.secret=examiesSecretKey123
jwt.expiration-ms=3600000
jwt.refresh-expiration-ms=86400000